server/auth/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', { 'template_name': 'auth/login.html' }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
)

server/waveonboarder/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

import onboarder.views as views
from api.views import *


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^api/tasks/(?:(?P<instance_id>\d+)/)?$', TaskResourceView.as_view(), name='api-task-resource'),
    url(r'^api/badges/(?:(?P<instance_id>\d+)/)?$', BadgeResourceView.as_view(), name='api-badge-resource'),
    url(r'^api/login/?$', LoginResourceView.as_view(), name='api-login-resource'),
    url(r'^api/logout/?$', LogoutResourceView.as_view(), name='api-logout-resource'),

    url(r'^auth/', include('auth.urls', namespace='auth')),

    url(r'^tasks/add/$', login_required(views.AddTaskView.as_view()), name='add_task'),
    url(r'^tasks/(?P<pk>\d+)/edit/$', login_required(views.EditTaskView.as_view()), name='edit_task'),
    url(r'^tasks/(?P<pk>\d+)/delete/$', login_required(views.DeleteTaskView.as_view()), name='delete_task'),
    url(r'^tasks/(?P<pk>\d+)/move-up/$', login_required(views.MoveUpView.as_view()), name='move_up'),
    url(r'^tasks/(?P<pk>\d+)/move-down/$', login_required(views.MoveDownView.as_view()), name='move_down'),
    url(r'^tasks/$', login_required(views.TasksView.as_view()), name='tasks'),

    url(r'^profiles/add/$', login_required(views.AddProfileView.as_view()), name='add_profile'),
    url(r'^profiles/(?P<pk>\d+)/edit/$', login_required(views.EditProfileView.as_view()), name='edit_profile'),
    url(r'^profiles/(?P<profile_id>\d+)/delete/$', login_required(views.EditProfileView.as_view()), name='delete_profile'),
    url(r'^profiles/$', login_required(views.ProfilesView.as_view()), name='profiles'),

    url(r'^recruits/add/$', login_required(views.AddRecruitView.as_view()), name='add_recruit'),
    url(r'^recruits/(?P<pk>\d+)/edit/$', login_required(views.EditRecruitView.as_view()), name='edit_recruit'),

    url(r'^random-facts/$', login_required(views.FactsView.as_view()), name='facts'),
    url(r'^random-facts/add/$', login_required(views.AddFactView.as_view()), name='add_fact'),
    url(r'^random-facts/(?P<pk>\d+)/edit/$', login_required(views.EditFactView.as_view()), name='edit_fact'),
)

server/onboarder/models.py
from django.db import models


class Badge(models.Model):
    name = models.CharField(max_length=50)
    image = models.CharField(max_length=100)
    
    def __unicode__(self):
        return u'{}'.format(self.name)


class Task(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=2000)
    pre_step = models.BooleanField(default=False)
    badge = models.ForeignKey(Badge, blank=True, null=True, related_name='tasks')
    image = models.CharField(max_length=100, blank=True)
    open_ended = models.BooleanField(default=False, verbose_name="Open-ended question?")

    class Meta:
        ordering = ['number']

class Profile(models.Model):
    name = models.CharField(max_length=50, verbose_name='Profile name')
    tasks = models.ManyToManyField(Task, related_name='profiles', blank=True)

    def member_list(self):
        return self.members.all()

    def total_tasks(self):
        return self.tasks.count()

    def __unicode__(self):
        return u'{}'.format(self.name)


class NewRecruit(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    start_date = models.DateField()
    job_title = models.CharField(max_length=50)
    profile = models.ForeignKey(Profile, related_name='members')

    def tasks_completed(self):
        return self.responses.count()

    def __unicode__(self):
        return u'{}'.format(self.name)


class Choice(models.Model):
    text = models.CharField(max_length=250)
    correct = models.BooleanField(default=False)
    task = models.ForeignKey(Task, related_name='choices', null=True)


class TaskStatus(models.Model):
    task = models.ForeignKey(Task, related_name='tasks', null=True)
    recruit = models.ForeignKey(NewRecruit, related_name='responses')
    complete = models.BooleanField(default=False)
    response = models.CharField(max_length=200, blank=True)


class RandomFact(models.Model):
    person = models.CharField(max_length=50)
    fact = models.CharField(max_length=250)
    picture = models.CharField(max_length=250)

server/onboarder/forms.py
import django.forms as forms
from django.forms.models import ModelMultipleChoiceField

from models import Task, Profile, NewRecruit, RandomFact
from widgets import CombinedButtonInput

INACTIVE_QUESTION = '<a href="#" class="btn btn-danger" data-toggle="{}" tabindex="-1"><i class="icon-remove"></i></a>'

class TaskForm(forms.ModelForm):
    choice1 = forms.CharField(max_length=250, label='', required=False,
        widget=CombinedButtonInput(prepend=INACTIVE_QUESTION.format(1)))
    choice2 = forms.CharField(max_length=250, label='', required=False,
        widget=CombinedButtonInput(prepend=INACTIVE_QUESTION.format(2)))
    choice3 = forms.CharField(max_length=250, label='', required=False,
        widget=CombinedButtonInput(prepend=INACTIVE_QUESTION.format(3)))
    choice4 = forms.CharField(max_length=250, label='', required=False,
        widget=CombinedButtonInput(prepend=INACTIVE_QUESTION.format(4)))
    
    correct_choice = forms.CharField(max_length=1, widget=forms.HiddenInput(),
        initial=1)
    profiles = forms.ModelMultipleChoiceField(queryset=Profile.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'unstyled'}))

    class Meta:
        model = Task
        widgets = {
            'description': forms.widgets.Textarea()
        }
        exclude = ('number')

    def clean_correct_choice(self):
        choice = self.cleaned_data['correct_choice']
        choices = [ self.cleaned_data['choice1'], self.cleaned_data['choice2'],
                self.cleaned_data['choice3'], self.cleaned_data['choice4']]
        c_int = int(choice) - 1

        if c_int < 0 or c_int > 3:
            self._errors['correct_choice'] = "Invalid choice"

        if [ c for c in choices if c ] and not choices[c_int]:
            self._errors['correct_choice'] = "Correct choice is blank"

        return choice


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile


class RecruitForm(forms.ModelForm):
    class Meta:
        model = NewRecruit


class FactForm(forms.ModelForm):
    class Meta:
        model = RandomFact

server/onboarder/views.py
import sys

from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, UpdateView, CreateView
from django.shortcuts import redirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.core.exceptions import ObjectDoesNotExist

from forms import TaskForm, ProfileForm, RecruitForm, FactForm
from models import Task, Profile, NewRecruit, RandomFact, Choice


class TasksView(ListView):
    template_name = 'onboarder/tasks.html'
    model = Task
    context_object_name = 'tasks'



class AddTaskView(FormView):
    template_name = 'onboarder/add_task.html'
    form_class = TaskForm

    def form_valid(self, form):
        task = form.instance
        try:
            last_task = Task.objects.order_by('-number')[0]
            task.number = last_task.number + 1
        except IndexError:
            task.number = 0

        task.save()

        task.profiles.add(*form.cleaned_data['profiles'])
        
        for choice in ['choice1', 'choice2', 'choice3', 'choice4']:
            if form.cleaned_data[choice]:
                Choice.objects.create(text=form.cleaned_data[choice],
                    correct=form.cleaned_data['correct_choice'] == choice[-1],
                    task=task)

        return redirect(reverse('tasks'))


class EditTaskView(UpdateView):
    template_name = 'onboarder/edit_task.html'
    form_class = TaskForm
    model = Task
    context_object_name = 'task'

    def get_initial(self):
        initial = super(EditTaskView, self).get_initial()
        task = self.get_object()
        initial['profiles'] = task.profiles.all()
        for c, i in zip(task.choices.all(), xrange(1, sys.maxint)):
            initial['choice' + str(i)] = c.text
            if c.correct:
                initial['correct_choice'] = str(i)
        return initial

    def get_context_data(self, **kwargs):
        context = super(EditTaskView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        task = form.instance
        task.save()

        # this is ghetto, I know
        task.profiles.clear()
        task.profiles.add(*form.cleaned_data['profiles'])
        task.choices.clear()

        for choice in ['choice1', 'choice2', 'choice3', 'choice4']:
            if form.cleaned_data[choice]:
                Choice.objects.create(text=form.cleaned_data[choice],
                    correct=form.cleaned_data['correct_choice'] == choice[-1],
                    task=task)

        return redirect(reverse('tasks'))


class DeleteTaskView(View):
    def get(self, request, pk):
        Task(pk=pk).delete()
        return redirect(reverse('tasks'))


class MoveUpView(View):
    def get(self, request, pk):
        task = Task.objects.get(pk=pk)
        if task.number:
            task_above = Task.objects.get(number=task.number-1)
            task_above.number, task.number = task.number, task_above.number
            task_above.save()
            task.save()
        return redirect(reverse('tasks'))

class MoveDownView(View):
    def get(self, request, pk):
        task = Task.objects.get(pk=pk)
        try:
            task_below = Task.objects.get(number=task.number+1)
            task_below.number, task.number = task.number, task_below.number
            task_below.save()
            task.save()
        except ObjectDoesNotExist:
            pass
        
        return redirect(reverse('tasks'))

class ProfilesView(ListView):
    template_name = 'onboarder/profiles.html'
    model = Profile
    context_object_name = 'profiles'


class AddProfileView(CreateView):
    template_name = 'onboarder/add_profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('profiles')


class EditProfileView(UpdateView):
    template_name = 'onboarder/edit_profile.html'
    form_class = ProfileForm
    model = Profile
    context_object_name = 'profile'
    success_url = reverse_lazy('profiles')


class AddRecruitView(CreateView):
    template_name = 'onboarder/add_recruit.html'
    form_class = RecruitForm
    success_url = reverse_lazy('profiles')
    

class EditRecruitView(UpdateView):
    template_name = 'onboarder/edit_recruit.html'
    form_class = RecruitForm
    model = NewRecruit
    context_object_name = 'recruit'
    success_url = reverse_lazy('profiles')


class FactsView(ListView):
    template_name = 'onboarder/facts.html'
    model = RandomFact
    context_object_name = 'facts'


class AddFactView(CreateView):
    template_name = 'onboarder/add_fact.html'
    form_class = FactForm
    success_url = reverse_lazy('facts')


class EditFactView(UpdateView):
    template_name = 'onboarder/edit_fact.html'
    form_class = FactForm
    model = RandomFact
    context_object_name = 'fact'
    success_url = reverse_lazy('facts')

server/templates/onboarder/_taskform.html
{% extends 'common/layout.html' %}
{% load commontags %}
{% load wysiwyg %}

{% block extrahead %}
{% wysiwyg_setup %}
{% endblock %}

{% block content %}
<div class="page-header">
    <h1>{% block pagetitle %}{% endblock %}</h1>
    <p class="lead">{% block pagelead %}{% endblock %}</p>
</div>
<form method="post" id="task-form">
    <div class="row">
        <div class="span6">
            {% display_field form.title %}
            <div class="pull-right pre-first-day">
                <label>Pre-first-day-task?</label>
                {{ form.pre_step }}
            </div>
            {% display_field form.description %}
            {% display_field form.badge %}
            {% display_field form.image %}
            {% display_field form.open_ended %}
        </div>
        <div class="span6">&nbsp;</div>
         <div class="span8 profile-list">
            <div class="span8">
                <h4>Profiles to which this task is assigned #greatgrammarbro</h4>
                {% if form.errors.profiles %}
                <p class="alert alert-error gutter-right2">Please select at least one profile.</p>
                {% endif %}
            </div>
            {{ form.profiles }}
        </div>
        <div class="span8 mc">
            <div class="span8">
                <h4>Les choix</h4>
                {% if form.errors.correct_choice %}
                <p class="alert alert-error gutter-right2">Please select which choice below shall be the correct one.</p>
                {% endif %}
                <p class="gutter-right">Choices are optional, but if you do provide some, make sure there are at least two and that you assign one as the correct choice.</p>
            </div>
            {% display_field form.is_question %}
            {% display_field form.choice1 %}
            {% display_field form.choice2 %}
            {% display_field form.choice3 %}
            {% display_field form.choice4 %}
            {{ form.correct_choice }}
        </div>
    </div>
    <div class="form-actions clearfix">
        <button type="submit" class="btn btn-primary"/>{% block buttontext %}{% endblock %}</button>
        <a class="btn btn-link" href="{% url 'tasks' %}">Cancel</a>
    </div>
    {% csrf_token %}
    {% wysiwyg_editor "id_description" %}
</form>
{% endblock %}

server/templates/onboarder/add_fact.html
{% extends 'common/layout.html' %}
{% load commontags %}

{% block content %}
<div class="page-header">
    <h1>Add a random fact</h1>
    <p class="lead">There are squirrels in the trees.</p>
</div>
<form method="post" id="task-form">
    <div class="row">
        <div class="span6">
            {% display_field form.person %}
            {% display_field form.fact %}
            {% display_field form.picture %}
        </div>
    </div>
    <div class="form-actions clearfix">
        <button type="submit" class="btn btn-primary"/>Add fact</button>
        <a class="btn btn-link" href="{% url 'facts' %}">Cancel</a>
    </div>
    {% csrf_token %}
</form>
{% endblock %}

server/templates/onboarder/add_profile.html
{% extends 'common/layout.html' %}
{% load commontags %}

{% block content %}
<div class="page-header">
    <h1>Create a new profile</h1>
    <p class="lead">The world is your oyster. Unless you're allergic to shellfish.</p>
</div>
<form method="post" id="task-form">
    <div class="row">
        <div class="span6">
            {% display_field form.name %}
        </div>
    </div>
    <div class="form-actions clearfix">
        <button type="submit" class="btn btn-primary"/>Create Profile</button>
        <a class="btn btn-link" href="{% url 'profiles' %}">Cancel</a>
    </div>
    {% csrf_token %}
</form>
{% endblock %}

server/templates/onboarder/add_recruit.html
{% extends 'common/layout.html' %}
{% load commontags %}

{% block content %}
<div class="page-header">
    <h1>Add a new recruit</h1>
    <p class="lead">Go easy on 'em. They're new.</p>
</div>
<form method="post" id="recruit-form">
    <div class="row">
        <div class="span6">
            {% display_field form.name %}
            {% display_field form.email %}
            {% display_field form.start_date %}
            {% display_field form.job_title %}
            {% display_field form.profile %}
        </div>
    </div>
    <div class="form-actions clearfix">
        <button type="submit" class="btn btn-primary"/>Create recruit</button>
        <a class="btn btn-link" href="{% url 'profiles' %}">Cancel</a>
    </div>
    {% csrf_token %}
</form>
{% endblock %}

server/templates/onboarder/add_task.html
{% extends 'onboarder/_taskform.html' %}

{% block pagetitle %}Create a new task{% endblock %}
{% block pagelead %}Hey man, this is where the magic happens.{% endblock %}

{% block buttontext %}Create task{% endblock %}

{% block pagejs %}
<script>
require(['jquery'], function($) { 
    {% if not form.errors %}
    /* pre-check profiles */
    if ($('.profile-list ul li input[type="checkbox"]:checked').length == 0) {
        $('.profile-list ul li input[type="checkbox"]').each(function(i, e) { 
            if ($(e).parent().text().trim().toLowerCase() == 'all')
                $(e).prop('checked', true);
        });
    }
    {% endif %}
    /* setup toggle on mc choices */
    $('.mc .input-prepend a').click(function() {
        if (!$(this).hasClass("btn-success")) {
            $('.mc .input-prepend a.btn-success')
                .removeClass('btn-success')
                .addClass('btn-danger')
                .find('i')
                .removeClass('icon-ok')
                .addClass('icon-remove');
            $(this).removeClass('btn-danger')
                .addClass('btn-success')
                .find('i')
                .removeClass('icon-remove')
                .addClass('icon-ok');
            $('#id_correct_choice').val($(this).data('toggle'));
        }
        return false;
    });
    /* preselect */
    $('.mc .input-prepend a').eq($('#id_correct_choice').val() - 1)
        .removeClass('btn-danger')
        .addClass('btn-success')
        .find('i')
        .removeClass('icon-remove')
        .addClass('icon-ok');
});
</script>
{% endblock %}

server/templates/onboarder/edit_fact.html
{% extends 'common/layout.html' %}
{% load commontags %}

{% block content %}
<div class="page-header">
    <h1>Edit {{ fact.person }}'s random fact</h1>
    <p class="lead">There are lies and damn lies. This is one of them.</p>
</div>
<form method="post" id="task-form">
    <div class="row">
        <div class="span6">
            {% display_field form.person %}
            {% display_field form.fact %}
            {% display_field form.picture %}
        </div>
    </div>
    <div class="form-actions clearfix">
        <button type="submit" class="btn btn-primary"/>Update</button>
        <a class="btn btn-link" href="{% url 'facts' %}">Cancel</a>
    </div>
    {% csrf_token %}
</form>
{% endblock %}

server/templates/onboarder/edit_profile.html
{% extends 'common/layout.html' %}
{% load commontags %}

{% block content %}
<div class="page-header">
    <h1>Update Profile {{ profile.name }}</h1>
    <p class="lead">You should have thought about this before. Just sayin'.</p>
</div>
<form method="post" id="task-form">
    <div class="row">
        <div class="span6">
            {% display_field form.name %}
        </div>
    </div>
    <div class="form-actions clearfix">
        <button type="submit" class="btn btn-primary"/>Update</button>
        <a class="btn btn-link" href="{% url 'profiles' %}">Cancel</a>
    </div>
    {% csrf_token %}
</form>
{% endblock %}

server/templates/onboarder/edit_recruit.html
{% extends 'common/layout.html' %}
{% load commontags %}

{% block content %}
<div class="page-header">
    <h1>Edit {{ recruit.name }}</h1>
    <p class="lead">Because they obviously aren't acceptable the way they are.</p>
</div>
<form method="post" id="recruit-form">
    <div class="row">
        <div class="span8">
            <div class="alert">{{ recruit.name }} has completed {{ recruit.tasks_completed }}/{{ recruit.profile.total_tasks }} tasks.</div>
            {% display_field form.name %}
            {% display_field form.email %}
            {% display_field form.start_date %}
            {% display_field form.job_title %}
            {% display_field form.profile %}
        </div>
    </div>
    <div class="form-actions clearfix">
        <button type="submit" class="btn btn-primary"/>Update</button>
        <a class="btn btn-link" href="{% url 'profiles' %}">Cancel</a>
    </div>
    {% csrf_token %}
</form>
{% endblock %}

server/templates/onboarder/edit_task.html
{% extends 'onboarder/_taskform.html' %}

{% block pagetitle %}Edit {{ task.title }}{% endblock %}
{% block pagelead %}Less magic, more fluff.{% endblock %}

{% block buttontext %}Update{% endblock %}

{% block pagejs %}
<script>
require(['jquery'], function($) { 
    /* setup toggle on mc choices */
    $('.mc .input-prepend a').click(function() {
        if (!$(this).hasClass("btn-success")) {
            $('.mc .input-prepend a.btn-success')
                .removeClass('btn-success')
                .addClass('btn-danger')
                .find('i')
                .removeClass('icon-ok')
                .addClass('icon-remove');
            $(this).removeClass('btn-danger')
                .addClass('btn-success')
                .find('i')
                .removeClass('icon-remove')
                .addClass('icon-ok');
            $('#id_correct_choice').val($(this).data('toggle'));
        }
        return false;
    });
    /* preselect */
    $('.mc .input-prepend a').eq($('#id_correct_choice').val() - 1)
        .removeClass('btn-danger')
        .addClass('btn-success')
        .find('i')
        .removeClass('icon-remove')
        .addClass('icon-ok');
});
</script>
{% endblock %}

server/templates/onboarder/facts.html
{% extends "common/layout.html" %}
{% load url from future %}
{% load static %}

{% block content %}

<blockquote>
    <p>I bet you could cut down on the hero factor in a place like this.</p>
    <small>Honey Bunny</small>
</blockquote>

<div class="row">
    <div class="facts-list span8 ">
        <h2>Random Facts</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Who</th>
                    <th>What</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                {% for f in facts %}
                    <tr>
                        <td><a href="{% url 'edit_fact' f.id %}">{{ f.person }}</a></td>
                        <td>{{ f.fact }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="well muted"><em>No facts. Add some.</em></td>
                    </tr>
                {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
</div>

<a href="{% url 'add_fact' %}" class="btn btn-primary">Add a random fact</a>

<p>&nbsp;</p>
{% endblock %}

server/templates/onboarder/profiles.html
{% extends "common/layout.html" %}
{% load url from future %}
{% load static %}

{% block content %}

<blockquote>
    <p>That's a pretty fucking good milkshake. I don't know if it's worth five dollars but it's pretty fucking good.</p>
    <small>Vincent Vega</small>
</blockquote>

<div class="row">
    <div class="profile-list span8">
        <h2>Profiles</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Members</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                {% for p in profiles %}
                    <tr>
                        <td><a href="{% url 'edit_profile' p.id %}">{{ p.name }}</a></td>
                        <td><span class="badge badge-{% if p.member_count > 0 %}info{% else %}warning{% endif %}">{{ p.member_list|length }}</span> &nbsp;{% for member in p.member_list %}<a href="{% url 'edit_recruit' member.id %}">{{ member }}</a> {% endfor %}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="well muted"><em>No profiles. Add one.</em></td>
                    </tr>
                {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
</div>

<a href="{% url 'add_profile' %}" class="btn btn-primary">Add a new profile</a>
<a href="{% url 'add_recruit' %}" class="btn btn-primary">Setup a new recruit</a>

<p>&nbsp;</p>
{% endblock %}

server/templates/onboarder/tasks.html
{% extends "common/layout.html" %}
{% load url from future %}
{% load static %}

{% block content %}

<blockquote>
    <p>If my answers frighten you then you should cease asking scary questions.</p>
    <small>Jules Winnfield</small>
</blockquote>

<div class="row">
    <div class="task-list thumbnails span8 ">
        <h2>Tasks</h2>
        {% for t in tasks %}
            <div class="task thumbnail">
                <span class="pull-left"><img src="{% static 'images/thumb.png' %}" /></span>
                <div class="controls pull-right">
                    <a href="{% url 'move_up' t.id %}"><i class="icon-arrow-up"></i></a>
                    <a href="{% url 'move_down' t.id %}"><i class="icon-arrow-down"></i></a>
                    <a href="{% url 'delete_task' t.id %}" onclick="return confirm('Are you sure you want to delete this task?');"><i class="icon-remove"></i></a>
                </div>
                <div class="pull-right badges">
                    {% for profile in t.profiles.all %}
                        <span class="label">{{ profile.name }}</span>
                    {% endfor %}
                    {% if t.pre_step %}
                    <span class="label label-info">Pre-Task</span>
                    {% endif %}
                </div>
                <div class="task-details">
                    <h4><a href="{% url 'edit_task' t.id %}">{{ t.title|truncatechars:30 }}</a></h4>
                    <p>{{ t.description|removetags:"a img p span div"|truncatechars:50 }}</p>
                </div>
            </div>
        {% empty %}
            <div class="task thumbnail muted">
                <em>There's not much to do without any tasks. Add one.</em>
            </div>
        {% endfor %}
    </div>
</div>

<a href="{% url 'add_task' %}" class="btn btn-primary">Add a Task</a>

<p>&nbsp;</p>
{% endblock %}