server/auth/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', { 'template_name': 'auth/login.html' }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
)

server/waveonboarder/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

import onboarder.views as views
from api.views import *


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^api/tasks/(?:(?P<instance_id>\d+)/)?$', TaskResourceView.as_view(), name='api-task-resource'),
    url(r'^api/badges/(?:(?P<instance_id>\d+)/)?$', BadgeResourceView.as_view(), name='api-badge-resource'),
    url(r'^api/login/?$', LoginResourceView.as_view(), name='api-login-resource'),
    url(r'^api/logout/?$', LogoutResourceView.as_view(), name='api-logout-resource'),

    url(r'^auth/', include('auth.urls', namespace='auth')),

    url(r'^tasks/add/$', login_required(views.AddTaskView.as_view()), name='add_task'),
    url(r'^tasks/(?P<pk>\d+)/edit/$', login_required(views.EditTaskView.as_view()), name='edit_task'),
    url(r'^tasks/(?P<pk>\d+)/delete/$', login_required(views.DeleteTaskView.as_view()), name='delete_task'),
    url(r'^tasks/(?P<pk>\d+)/move-up/$', login_required(views.MoveUpView.as_view()), name='move_up'),
    url(r'^tasks/(?P<pk>\d+)/move-down/$', login_required(views.MoveDownView.as_view()), name='move_down'),
    url(r'^tasks/$', login_required(views.TasksView.as_view()), name='tasks'),

    url(r'^profiles/add/$', login_required(views.AddProfileView.as_view()), name='add_profile'),
    url(r'^profiles/(?P<pk>\d+)/edit/$', login_required(views.EditProfileView.as_view()), name='edit_profile'),
    url(r'^profiles/(?P<profile_id>\d+)/delete/$', login_required(views.EditProfileView.as_view()), name='delete_profile'),
    url(r'^profiles/$', login_required(views.ProfilesView.as_view()), name='profiles'),

    url(r'^recruits/add/$', login_required(views.AddRecruitView.as_view()), name='add_recruit'),
    url(r'^recruits/(?P<pk>\d+)/edit/$', login_required(views.EditRecruitView.as_view()), name='edit_recruit'),

    url(r'^random-facts/$', login_required(views.FactsView.as_view()), name='facts'),
    url(r'^random-facts/add/$', login_required(views.AddFactView.as_view()), name='add_fact'),
    url(r'^random-facts/(?P<pk>\d+)/edit/$', login_required(views.EditFactView.as_view()), name='edit_fact'),
)

server/templates/common/layout.html
{% load static %}
{% load url from future %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}wave onboarder{% endblock %}</title>
    {% block pagecss %}{% endblock %}
    
    <link href="{% static 'lib/bootstrap/css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/common.css' %}" rel="stylesheet" />
    {% block extrahead %}{% endblock %}
</head>

<body>
    <div class="navbar navbar-fixed-top navbar-inverse">
            <div class="navbar-inner">
                <a class="brand" href="{% url 'tasks' %}">waveonboarder</a>
                {% if user.is_authenticated %}
                    <ul class="nav">
                        <li><a href="{% url 'tasks' %}"><i class="icon-tasks icon-white"></i> Tasks</a></li>
                        <li><a href="{% url 'profiles' %}"><i class="icon-user icon-white"></i> Profiles &amp; Users</a></li>
                        <li><a href="{% url 'facts' %}"><i class="icon-gift icon-white"></i> Random Facts</a></li>
                    </ul>
                    <ul class="nav pull-right">
                        <li><a href="{% url 'auth:logout' %}"><i class="icon-fire icon-white"></i> Logout</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
	<div class="container-fluid span8 offset4">
        {% block content %}Snap.{% endblock %}
	</div>
    <script src="/static/lib/require.js"> </script>
    <script>
        require.config({
            paths: {
                jquery : "http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min",
                bootstrap: '../lib/bootstrap/js/bootstrap.min'
            },
            shim: {
                'bootstrap': {deps: ['jquery']}
            }
        });
    </script>
    {% block pagejs %}{% endblock %}
</body>
</html>